### ISSUE TITLE
Update process?

### ISSUE THREAD

**Issue by artisin** [cloudron-io/mattermost-app#1]
@gramakri I noticed you are working on the 3+ update that is needed in order for mobile capability. What is the update process for existing clients?

**Comment by gramakri** [comment]
@artisin We need to follow up on https://github.com/mattermost/platform/issues/2929. Currently, mattermost on Cloudron runs with a small patch. We will try to get mattermost updated this week.

**Comment by gramakri** [comment]
@artisin I pushed an update.
